-- MySQL Script generated by MySQL Workbench
-- Thu May 24 15:34:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `hotels` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hotels` ;

DROP TABLE IF EXISTS `hotels`.`administrator`;

CREATE TABLE `hotels`.`administrator` (
  `Username_of_Admin` VARCHAR(45) NOT NULL,
  `Password_of_Admin` VARCHAR(45) NOT NULL,  
  `Admin_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Admin_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`customer`;

CREATE TABLE `hotels`.`customer` (
  `First_Name_C` VARCHAR(45) NOT NULL,
  `SSN_C` VARCHAR(9) NOT NULL UNIQUE,
  `Last_Name_C` VARCHAR(45) NOT NULL,
  `IRS_C` VARCHAR(9) NOT NULL,
  `A_Street_C` VARCHAR(45) NOT NULL,
  `A_Number_C` VARCHAR(10) NOT NULL,
  `A_Postal_Code_C` VARCHAR(45) NOT NULL,
  `A_City_C` VARCHAR(45) NOT NULL,
  `First_Registration_C` DATETIME NOT NULL DEFAULT LOCALTIME(),
  `User_C` VARCHAR(45) UNIQUE NOT NULL,
  `Pass_C` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IRS_C`),
  INDEX `username_idx` (`User_C` ASC),
  INDEX `password_idx` (`Pass_C` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP VIEW IF EXISTS `hotels`.`cust`;

CREATE VIEW `hotels`.`cust`
AS SELECT First_Name_C, Last_Name_C, IRS_C, SSN_C, A_Street_C, A_Number_C, A_Postal_Code_C, A_City_C, First_Registration_C
FROM `hotels`.`customer`;

DROP TABLE IF EXISTS `hotels`.`hotel_group`;

CREATE TABLE `hotels`.`hotel_group` (
  `A_Street_HG` VARCHAR(45) NOT NULL,
  `A_Number_HG` VARCHAR(10) NOT NULL,
  `A_Postal_Code_HG` VARCHAR(45) NOT NULL,
  `A_City_HG` VARCHAR(45) NOT NULL,
  `Hotel_Group_ID` INT(45) NOT NULL AUTO_INCREMENT,
  `Number_of_Hotels` INT(11) DEFAULT 0,
  `Name_HG` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`Hotel_Group_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




DROP TABLE IF EXISTS `hotels`.`hotel`;

CREATE TABLE `hotels`.`hotel` (
  `Stars` TINYINT(1) NOT NULL,
  `Number_of_Rooms` INT(11) DEFAULT 0,
  `Hotel_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `A_Street_H` VARCHAR(45) NOT NULL,
  `A_Number_H` VARCHAR(10) NOT NULL,
  `A_Postal_Code_H` VARCHAR(45) NOT NULL,
  `A_City_H` VARCHAR(45) NULL DEFAULT NULL,
  `Hotel_Group_ID_H` INT(11) NOT NULL,
  `Name_H` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`Hotel_ID`),
  INDEX `Parent_Hotel_Group_idx` (`Hotel_Group_ID_H` ASC),
  CONSTRAINT `Parent_Hotel_Group`
    FOREIGN KEY (`Hotel_Group_ID_H`)
    REFERENCES `hotels`.`hotel_group` (`Hotel_Group_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`email_hotel`;

CREATE TABLE `hotels`.`email_hotel` (
  `Hotel_ID_email` INT(11) NOT NULL,
  `Email_H` VARCHAR(45) NOT NULL,
  `Email_H_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Email_H_ID`),
  INDEX `Hotel_ID (email)` (`Hotel_ID_email` ASC),
  CONSTRAINT `Hotel_ID (email)`
    FOREIGN KEY (`Hotel_ID_email`)
    REFERENCES `hotels`.`hotel` (`Hotel_ID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`email_hotel_group`;

CREATE TABLE `hotels`.`email_hotel_group` (
  `Hotel_Group_ID_email` INT(11) NOT NULL,
  `Email_HG` VARCHAR(45) NOT NULL,
  `Email_HG_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Email_HG_ID`),
  INDEX `Hotel_Group_ID (email)_idx` (`Hotel_Group_ID_email` ASC),
  CONSTRAINT `Hotel_Group_ID (email)`
    FOREIGN KEY (`Hotel_Group_ID_email`)
    REFERENCES `hotels`.`hotel_group` (`Hotel_Group_ID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



DROP TABLE IF EXISTS `hotels`.`employee`;

CREATE TABLE `hotels`.`employee` (
  `First_Name_E` VARCHAR(45) NOT NULL,
  `SSN_E` CHAR(9) NOT NULL,
  `Last_Name_E` VARCHAR(45) NOT NULL,
  `IRS_E` VARCHAR(9) NOT NULL,
  `A_Street_E` VARCHAR(45) NOT NULL,
  `A_Number_E` VARCHAR(10) NOT NULL,
  `A_Postal_Code_E` VARCHAR(45) NOT NULL,
  `A_City_E` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IRS_E`)
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



DROP TABLE IF EXISTS `hotels`.`hotel_room`;

CREATE TABLE `hotels`.`hotel_room` (
  `Room_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Price` FLOAT NOT NULL,
  `Capacity` INT(11) NOT NULL,
  `Expandable` ENUM('None', 'Bed', 'Room', 'Both') NOT NULL,
  `Hotel_ID_R` INT(11) NOT NULL,
  `Sea_View` ENUM('Yes','No') DEFAULT 'No',
  `Balcony` ENUM('Yes','No') DEFAULT 'No',
  `Smoking` ENUM('Yes','No') DEFAULT 'No',
  `Parking` ENUM('Yes','No') DEFAULT 'No',
  `Wifi` ENUM('Yes','No') DEFAULT 'No',
  `TV` ENUM('Yes','No') DEFAULT 'No',
  `Refridgerator` ENUM('Yes','No') DEFAULT 'No',
  `Air_Conditioning` ENUM('Yes','No') DEFAULT 'No',
  `Repairs_Needed` ENUM('Yes','No') DEFAULT 'No',
  PRIMARY KEY (`Room_ID`),
  INDEX `Has_Rooms_idx` (`Hotel_ID_R` ASC),
  CONSTRAINT `Parent_Hotel`
    FOREIGN KEY (`Hotel_ID_R`)
    REFERENCES `hotels`.`hotel` (`Hotel_ID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE hotel_room AUTO_INCREMENT=100;


DROP TABLE IF EXISTS `hotels`.`phone_hotel`;

CREATE TABLE `hotels`.`phone_hotel` (
  `Phone_H` VARCHAR(45) NOT NULL,
  `Phone_H_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Hotel_ID_phone` INT(11) NOT NULL,
  PRIMARY KEY (`Phone_H_ID`),
  INDEX `Hotel_ID (phone)` (`Hotel_ID_phone` ASC),
  CONSTRAINT `Hotel_ID (phone)`
    FOREIGN KEY (`Hotel_ID_phone`)
    REFERENCES `hotels`.`hotel` (`Hotel_ID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



DROP TABLE IF EXISTS `hotels`.`phone_hotel_group`;

CREATE TABLE `hotels`.`phone_hotel_group` (
  `Phone_HG` VARCHAR(45) NOT NULL,
  `Phone_HG_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Hotel_Group_ID_phone` INT(11) NOT NULL,
  PRIMARY KEY (`Phone_HG_ID`),
  INDEX `Hotel_Group_ID (phone)` (`Hotel_Group_ID_phone` ASC),
  CONSTRAINT `Hotel_Group_ID (phone)`
    FOREIGN KEY (`Hotel_Group_ID_phone`)
    REFERENCES `hotels`.`hotel_group` (`Hotel_Group_ID`)
	ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`rents`;

CREATE TABLE `hotels`.`rents` (
  `Start_Date` DATE NOT NULL,
  `Finish_Date` DATE NOT NULL,
  `Payment_Amount` FLOAT NOT NULL,
  `Payment_Method` ENUM('Cash','Card') NOT NULL,
  `IRS_C_rents` VARCHAR(9) NOT NULL,
  `IRS_E_rents` VARCHAR(9) NOT NULL,
  `Room_ID_rents` INT(11) NOT NULL,
  PRIMARY KEY (`Room_ID_rents`, `Start_Date`, `Finish_Date`),
  INDEX `Room_ID_idx` (`Room_ID_rents` ASC),
  INDEX `Start_Date_ID_idx` (`Start_Date` ASC),
  INDEX `Finish_Date_ID_idx` (`Finish_Date` ASC),
  CONSTRAINT `Customer_ID (rents)`
    FOREIGN KEY (`IRS_C_rents`)
    REFERENCES `hotels`.`customer` (`IRS_C`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Employee_ID (rents)`
    FOREIGN KEY (`IRS_E_rents`)
    REFERENCES `hotels`.`employee` (`IRS_E`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Room_ID (rents)`
    FOREIGN KEY (`Room_ID_rents`)
    REFERENCES `hotels`.`hotel_room` (`Room_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `hotels`.`backup`;

CREATE TABLE `hotels`.`backup` (
  `Start_Date_back` DATE NOT NULL,
  `Finish_Date_back` DATE NOT NULL,
  `Payment_Amount_back` FLOAT NOT NULL,
  `Payment_Method_back` VARCHAR(20) NOT NULL,
  `IRS_C_rents_back` VARCHAR(9) NOT NULL,
  `IRS_E_rents_back` VARCHAR(9) NOT NULL,
  `Room_ID_rents_back` INT(11) NOT NULL,
  `Backup_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Backup_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`reserves`;

CREATE TABLE `hotels`.`reserves` (
  `Start_Date` DATE NOT NULL,
  `Finish_Date` DATE NOT NULL,
  `Paid` ENUM('Yes','No') DEFAULT 'No',
  `IRS_C_reserves` VARCHAR(9) NOT NULL,
  `Room_ID_reserves` INT(11) NOT NULL,
  PRIMARY KEY (`Room_ID_reserves`,`Start_Date`,`Finish_Date`),
  INDEX `Start_Date_idx` (`Start_Date` ASC),
  INDEX `Finish_Date_idx` (`Finish_Date` ASC),
  INDEX `Room_ID_reserves_idx` (`Room_ID_reserves` ASC),
  INDEX `Paid_idx` (`Paid` ASC),
  CONSTRAINT `Customer_ID_`
    FOREIGN KEY (`IRS_C_reserves`)
    REFERENCES `hotels`.`customer` (`IRS_C`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Room_ID_`
    FOREIGN KEY (`Room_ID_reserves`)
    REFERENCES `hotels`.`hotel_room` (`Room_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `hotels`.`history`;

CREATE TABLE `hotels`.`history` (
  `Start_Date_hist` DATE NOT NULL,
  `Finish_Date_hist` DATE NOT NULL,
  `Paid_hist` ENUM('Yes','No') DEFAULT 'No',
  `IRS_C_hist` VARCHAR(9) NOT NULL,
  `Room_ID_hist` INT(11) NOT NULL,
  `History_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`History_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `hotels`.`works`;

CREATE TABLE `hotels`.`works` (
  `Start_Date` DATE NOT NULL,
  `Finish_Date` DATE NOT NULL,
  `Job_Position` VARCHAR(45) NOT NULL,
  `IRS_E_works` VARCHAR(9) NOT NULL,
  `Hotel_ID_works` INT(11) NOT NULL,
  `Works_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Works_ID`),
  INDEX `IRS_E_idx` (`IRS_E_works` ASC),
  INDEX `Hotel_ID_idx` (`Hotel_ID_works` ASC),
  CONSTRAINT `Hotel_ID`
    FOREIGN KEY (`Hotel_ID_works`)
    REFERENCES `hotels`.`hotel` (`Hotel_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IRS_E`
    FOREIGN KEY (`IRS_E_works`)
    REFERENCES `hotels`.`employee` (`IRS_E`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP VIEW IF EXISTS hotels.`search_table`;

CREATE VIEW hotels.`search_table`
AS SELECT Room_ID, Price, Capacity, Expandable, Hotel_ID_R, Sea_View, Balcony, Smoking, Parking, Wifi, TV, Refridgerator, Air_Conditioning, Repairs_Needed, Stars, Hotel_ID, A_City_H, Name_H, Hotel_Group_ID_H, Hotel_Group_ID, Name_HG FROM hotel_room
JOIN hotel ON hotel.Hotel_ID = hotel_room.Hotel_ID_R
JOIN hotel_group ON hotel_group.Hotel_Group_ID = hotel.Hotel_Group_ID_H;

DROP VIEW IF EXISTS hotels.`employee_reservations`;

CREATE VIEW hotels.`employee_reservations`
AS SELECT Start_Date, Finish_Date, Paid, IRS_C_reserves, Room_ID_reserves, Room_ID, Hotel_ID_R FROM reserves
JOIN hotel_room ON Room_ID = Room_ID_reserves;


DROP VIEW IF EXISTS hotels.`cities`;

CREATE VIEW hotels.`cities`
AS SELECT DISTINCT A_City_H FROM hotel;

DELIMITER |
CREATE TRIGGER `reserveshistory` AFTER INSERT ON reserves FOR EACH ROW BEGIN
INSERT INTO history (Start_Date_hist, Finish_Date_hist, Paid_hist, IRS_C_hist, Room_ID_hist)
VALUES (NEW.Start_Date, NEW.Finish_Date, NEW.Paid, NEW.IRS_C_reserves, NEW.Room_ID_reserves);
END;
|
delimiter ;

delimiter |
CREATE TRIGGER `rentsbackup` AFTER INSERT ON rents FOR EACH ROW BEGIN
INSERT INTO backup (Start_Date_back, Finish_Date_back, IRS_C_rents_back, Room_ID_rents_back, Payment_Amount_back, Payment_Method_back, IRS_E_rents_back)
VALUES (NEW.Start_Date, NEW.Finish_Date, NEW.IRS_C_rents, NEW.Room_ID_rents, NEW.Payment_Amount, NEW.Payment_Method, NEW.IRS_E_rents);
END;
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER `incrementhotels` BEFORE INSERT ON hotel FOR EACH ROW BEGIN
UPDATE hotel_group SET Number_of_Hotels = Number_of_Hotels+1 WHERE Hotel_Group_ID=NEW.Hotel_Group_ID_H;
END;
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER `decrementhotels` BEFORE DELETE ON hotel FOR EACH ROW BEGIN
UPDATE hotel_group SET Number_of_Hotels = Number_of_Hotels-1 WHERE Hotel_Group_ID=OLD.Hotel_Group_ID_H;
END;
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER `incrementrooms` BEFORE INSERT ON hotel_room FOR EACH ROW BEGIN
UPDATE hotel SET Number_of_Rooms = Number_of_Rooms+1 WHERE Hotel_ID=NEW.Hotel_ID_R;
END;
|
DELIMITER ;

DELIMITER |
CREATE TRIGGER `decrementrooms` BEFORE DELETE ON hotel_room FOR EACH ROW BEGIN
UPDATE hotel SET Number_of_Rooms = Number_of_Rooms-1 WHERE Hotel_ID=OLD.Hotel_ID_R;
END;
|
DELIMITER ;


DELIMITER ;;
/* IRS OF EACH EMPLOYEE MUST BE A 9-DIGIT CODE ELSE ERROR*/
CREATE DEFINER=`root`@`localhost` TRIGGER `check_irs_e` BEFORE INSERT ON `employee` FOR EACH ROW BEGIN
          IF length(NEW.IRS_E) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of employee';
          END IF;
     END ;;
CREATE  DEFINER=`root`@`localhost`  TRIGGER `check_update_irs_e` BEFORE UPDATE ON `employee` FOR EACH ROW BEGIN
          IF length(NEW.IRS_E) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of employee';
          END IF;
     END ;;
DELIMITER ;

DELIMITER ;;
/* IRS OF EACH EMPLOYEE MUST BE A 9-DIGIT CODE ELSE ERROR*/
CREATE DEFINER=`root`@`localhost` TRIGGER `check_ssn_e` BEFORE INSERT ON `employee` FOR EACH ROW BEGIN
          IF length(NEW.SSN_E) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid SSN of employee';
          END IF;
     END ;;
CREATE  DEFINER=`root`@`localhost`  TRIGGER `check_update_ssn_e` BEFORE UPDATE ON `employee` FOR EACH ROW BEGIN
          IF length(NEW.SSN_E) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid SSN of employee';
          END IF;
     END ;;
DELIMITER ;


DELIMITER ;;
/* IRS OF EACH CUSTOMER MUST BE A 9-DIGIT CODE ELSE ERROR*/
CREATE DEFINER=`root`@`localhost` TRIGGER `check_irs_c` BEFORE INSERT ON `customer` FOR EACH ROW BEGIN
          IF length(NEW.IRS_C) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of customer';
          END IF;
     END ;;
CREATE  DEFINER=`root`@`localhost`  TRIGGER `check_update_irs_c` BEFORE UPDATE ON `customer` FOR EACH ROW BEGIN
          IF length(NEW.IRS_C) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of customer';
          END IF;
     END ;;
DELIMITER ;

DELIMITER ;;
/* IRS OF EACH CUSTOMER MUST BE A 9-DIGIT CODE ELSE ERROR*/
CREATE DEFINER=`root`@`localhost` TRIGGER `check_ssn_c` BEFORE INSERT ON `customer` FOR EACH ROW BEGIN
          IF length(NEW.SSN_C) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of customer';
          END IF;
     END ;;
CREATE  DEFINER=`root`@`localhost`  TRIGGER `check_update_ssn_c` BEFORE UPDATE ON `customer` FOR EACH ROW BEGIN
          IF length(NEW.SSN_C) != 9
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid IRS of customer';
          END IF;
     END ;;
DELIMITER ;




DELIMITER ;;
/* EMAIL OF EACH HOTEL GROUP MUST BE IN THE CORRECT FORM ELSE ERROR*/
CREATE  DEFINER=`root`@`localhost`  TRIGGER `check_mail_hg` BEFORE INSERT ON `email_hotel_group` FOR EACH ROW BEGIN
          IF NEW.Email_HG NOT LIKE '%_@__%.__%'
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid mail';
          END IF;
     END ;;

CREATE DEFINER=`root`@`localhost`  TRIGGER `check_update_mail_hg` BEFORE UPDATE ON `email_hotel_group` FOR EACH ROW BEGIN
          IF NEW.Email_HG NOT LIKE '%_@__%.__%'
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid mail';
          END IF;
     END ;;
DELIMITER ;


DELIMITER ;;
/* EMAIL OF EACH HOTEL MUST BE IN THE CORRECT FORM ELSE ERROR*/
 CREATE DEFINER=`root`@`localhost`TRIGGER `check_mail_h` BEFORE INSERT ON `email_hotel` FOR EACH ROW BEGIN
          IF NEW.Email_H NOT LIKE '%_@__%.__%'
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid mail';
          END IF;
     END ;;
SET SESSION SQL_MODE="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO";;
CREATE DEFINER=`root`@`localhost` TRIGGER `check_update_mail_h` BEFORE UPDATE ON `email_hotel` FOR EACH ROW BEGIN
          IF NEW.Email_H NOT LIKE '%_@__%.__%'
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'Invalid mail';
          END IF;
     END ;;
DELIMITER ;


DELIMITER ;;
/* START DATE < FINISH DATE ELSE ERROR */
CREATE DEFINER=`root`@`localhost` TRIGGER `validate__insert_end_date` BEFORE INSERT ON `works` FOR EACH ROW BEGIN
          IF (NEW.Start_Date IS NOT NULL AND NEW.Finish_date < NEW.Start_date)
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'End date can not be prior start date';
          END IF;
     END ;;
CREATE DEFINER=`root`@`localhost` TRIGGER `validate__updated_end_date` BEFORE UPDATE ON `works` FOR EACH ROW BEGIN
          IF (NEW.Finish_Date IS NOT NULL AND NEW.Finish_Date < NEW.Start_Date)
          THEN
               SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'End date can not be prior start date';
          END IF;
     END ;;
DELIMITER ;


/*
DELIMITER |


CREATE TRIGGER delete_hotel_triggers_delete_employees
AFTER DELETE ON works FOR EACH ROW BEGIN
DELETE FROM employee WHERE `employee`.`IRS_E` = OLD.`works`.`IRS_E_works`;
END;
|

DELIMITER ;
*/



INSERT INTO administrator (Username_of_Admin, Password_of_Admin)
VALUES 
('Admin', '12345678');

INSERT INTO hotel_group (A_Street_HG, A_Number_HG, A_Postal_Code_HG, A_City_HG, Name_HG)
VALUES 
('Aristeidou', '202', '11732', 'Piraeus','AccorHotels'),
('Kleomeni', '28', '28364', 'Athens', 'Hilton Worldwide'),
('Gkonou', '202', '11732', 'Glyfada', 'Coast Hotels'),
('Theofilou', '28', '28364', 'Palini', 'Mandarin Hotel Group'),
('Aflas', '32', '46280', 'Chania', 'Four Seasons Hotels and Resorts');

INSERT INTO email_hotel_group (Hotel_Group_ID_email, Email_HG)
VALUES
(1, 'Accor@gmail.com'),
(1, 'AccorHotels@gmail.com'),
(2, 'Hilton@gmail.com'),
(3, 'Mandarin@gmail.com'),
(4, 'CoastHotels@gmail.com'),
(5, 'FourSeasons@gmail.com'),
(4, 'CoastalHotels@gmail.com');

INSERT INTO phone_hotel_group (Hotel_Group_ID_phone, Phone_HG)
VALUES
(1, '0030 2107897844'),
(1, '0030 2107897843'),
(2, '0030 2102789394'),
(3, '0030 2103764824'), 
(4, '0030 2107939000'),
(5, '0030 6217939900');

INSERT INTO hotel (A_Street_H, A_Number_H, A_Postal_Code_H, A_City_H, Hotel_Group_ID_H, Stars, Name_H)
VALUES
('Kalenas', '25', '32973', 'Arachova', 5, 3, 'Snowy Tundra Resort & Spa'),
('Velantras', '20', '48326', 'Glyfada', 1 , 4, 'Cedar Hotel'),
('Stratigou Laggou', '20', '68344', 'Thessaloniki', 2 , 4, 'Crescent Resort'),
('Matogiannia', '46', '42398', 'Thessaloniki', 2 , 3, 'Denali Perch Resort'),
('Koniari', '32', '68534', 'Milos', 3 , 4, 'Enchanted Isle'),
('Merlis', '89', '10923', 'Milos', 3 , 3, 'Entrada Resort'),
('Tsilou', '10', '24323', 'Kithira', 4, 3, 'Fountainhead Reserve'),
('Kanellopoulou', '43', '54534', 'Amorgos', 4, 4, 'Sunny Harbor Hotel'),
('Leonidou', '23', '64324', 'Volos', 5, 4, 'Rose Obelisk Hotel'),
('Vlachou', '98', '68534', 'Folegandros', 5, 3, 'Panorama Resort'),
('Pithagora', '10', '42224', 'Patra', 1, 2, 'Oriental Loch Resort'),
('Dekelias', '49', '65223', 'Patra', 3, 5, 'Peaceful Bazaar Hotel'),
('Aspasias', '58', '64324', 'Tinos', 4, 5, 'Regal Dream Resort'),
('Rodon', '9', '60984', 'Skyros', 5, 5, 'Golden Nugget Resort & Spa'),
('Mimozas', '23', '60094', 'Mykonos', 2, 2, 'Crusty Crab'),
('Giasemion', '97', '36794', 'Zakynthos', 1, 3, 'Majestic Resort'),
('Dermetzili', '19', '28436', 'Zakynthos', 2, 1, 'Chum Bucket'),
('Mpizaniou', '3', '32190', 'Kerkyra', 4, 2, 'Pleasant Baron Resort'),
('Orfeos', '30', '42739', 'Koroni', 3, 5, 'Chateau Hotel'),
('Iras', '58', '24379', 'Gardiki', 2, 5, 'Revelation Resort & Spa'),
('Thetidos', '18', '43974', 'Volos', 5, 5, 'Refresh Resort & Spa'),
('Thiseos', '112', '48732', 'Santorini', 1, 4, 'Aqua Luxury Suites'),
('Irodotou', '49', '99904', 'Santorini', 3, 5, 'Kalntere Resort & Spa'),
('Iraklitou', '29', '15324', 'Mykonos', 4, 3, 'Tranquil Petal Resort & Spa'),
('Pallados', '5', '39284', 'Glyfada', 1, 3, 'Monsoon Resort');

INSERT INTO email_hotel (Hotel_ID_email, Email_H)
VALUES
(1, 'SnowyTundra@gmail.com'),
(2 ,'Cedar@gmail.com'),
(3 ,'Crescent@gmail.com'),
(4 ,'DenaliPerch@gmail.com'),
(5 ,'Enchanted@gmail.com'),
(6 ,'Entrada@gmail.com'),
(7 ,'Fountainhead@gmail.com'),
(8 ,'SunnyHarbor@gmail.com'),
(9 ,'RoseObelisk@gmail.com'),
(10, 'Panorama@gmail.com'),
(11, 'OrientalLoch@gmail.com'),
(12, 'PeacefulBazaar@gmail.com'),
(20, 'StePalace@gmail.com'),
(13, 'RegalDream@gmail.com'),
(14, 'GoldenNugget@gmail.com'),
(15, 'CrustyCrab@gmail.com'),
(16, 'Majestic@gmail.com'),
(17, 'ChumBucket@gmail.com'),
(18, 'PleasantBaron@gmail.com'),
(19, 'Chateau@gmail.com'),
(20, 'Revelation@gmail.com'),
(21, 'Refresh@gmail.com'),
(22, 'AquaLuxury@gmail.com'),
(23, 'Revelation@gmail.com'),
(3, 'YeahScience@gmail.com'),
(24, 'TranquilPetal@gmail.com'),
(25, 'Monsoon@gmail.com'),
(3, 'YeahScience@gmail.com'),
(1, 'SunningTanning@gmail.com');

INSERT INTO phone_hotel (Hotel_ID_phone, Phone_H)
VALUES
(1, '0030 4342344583'),
(2, '0030 9828947366'),
(3, '0030 4824823679'),
(4, '0030 6538792458'),
(5, '0030 8123476234'),
(6, '0030 4283792349'),
(7, '0030 2438764328'),
(8, '0030 1923704239'),
(9, '0030 2398486749'),
(10, '0030 3928182908'),
(11, '0030 1247982342'),
(12, '0030 9243749298'),
(13, '0030 4298354682'),
(14, '0030 4923678948'),
(15, '0030 2239487238'),
(16, '0030 1293879213'),
(17, '0030 4238723499'),
(18, '0030 4239847299'),
(19, '0030 1928379213'),
(20, '0030 1239871230'),
(21, '0030 1293879230'),
(22, '0030 2934877599'),
(23, '0030 4782364823'),
(24, '0030 9234874929'),
(25, '0030 4823639420'),
(26, '0030 1293872394'),
(10, '0030 1298371239'),
(8, '0030 1923704238'),
(3, '0030 4824823678'),
(17, '0030 4238723498');


INSERT INTO hotel_room(Price, Capacity, Expandable, Hotel_ID_R, Sea_View, Balcony, Smoking, Parking, Wifi, TV, Refridgerator, Air_Conditioning, Repairs_Needed)
VALUES
(100, 1, 'None', 1, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(200, 2, 'Room', 1, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(300, 3, 'Bed', 1, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(350, 4, 'Bed', 1, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(132, 3, 'Both', 1, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(80, 1, 'Both', 2, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(30, 2, 'Both', 2, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 3, 'None',2, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 4, 'Bed', 2, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 4, 'Bed', 2, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(32, 1, 'Bed', 3, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(500, 2, 'None', 3, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(800, 3, 'None', 3, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(799, 4, 'Room', 3, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(424, 3, 'None', 3, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(312, 1, 'Room', 4, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(190, 2, 'Bed', 4, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(362, 3, 'Bed', 4, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(135, 4, 'Both', 4, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(100, 2, 'Both', 4, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(92, 1, 'Both', 5, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 1, 'None', 5, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 2, 'Bed', 5, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 3, 'Bed', 5, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(53, 4, 'Bed', 5, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(98, 1, 'None', 6, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(53, 2, 'None', 6, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(48, 3, 'Room', 6, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(100, 4, 'None', 6, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(200, 2, 'Room', 6, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(300, 3, 'Bed', 7, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(350, 4, 'Bed', 7, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(132, 4, 'Both', 7, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(80, 2, 'Both', 7, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(30, 1, 'Both', 7, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 1, 'None',8, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 3, 'Bed', 8, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 2, 'Bed', 8, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(32, 1, 'Bed', 8, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(500, 4, 'None', 8, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(800, 3, 'None', 9, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(799, 2, 'Room', 9, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(424, 2, 'None', 9, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(312, 1, 'Room', 9, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(190, 4, 'Bed', 9, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(362, 4, 'Bed', 10, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(135, 3, 'Both', 10, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(100, 2, 'Both', 10, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(92, 2, 'Both', 10, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 1, 'None', 10, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 1, 'Bed', 11, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 1, 'Bed', 11, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(53, 2, 'Bed', 11, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(98, 4, 'None', 11, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(53, 3, 'None', 11, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(100, 1, 'None', 12, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(200, 2, 'Room', 12, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(300, 3, 'Bed', 12, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(350, 4, 'Bed', 12, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(132, 1, 'Both', 12, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(80, 4, 'Both', 13, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(30, 1, 'Both', 13, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 2, 'None',13, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 3, 'Bed', 13, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 3, 'Bed', 13, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(32, 1, 'Bed', 14, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(500, 3, 'None', 14, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(84, 2, 'None', 14, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(799, 4, 'Room', 14, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(424, 3, 'None', 14, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(312, 2, 'Room', 15, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(190, 3, 'Bed', 15, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(362, 4, 'Bed', 15, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(135, 3, 'Both', 15, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(100, 1, 'Both', 15, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(92, 4, 'Both', 16, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 1, 'None', 16, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 2, 'Bed', 16, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 1, 'Bed', 16, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(53, 3, 'Bed', 16, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(98, 2, 'None', 17, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(53, 1, 'None', 17, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(48, 1, 'Room', 17, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(100, 3, 'None', 17, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(200, 4, 'Room', 17, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(300, 3, 'Bed', 18, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(350, 4, 'Bed', 18, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(132, 2, 'Both', 18, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(80, 1, 'Both', 18, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(30, 1, 'Both', 18, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 2, 'None',19, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(53, 3, 'Bed', 19, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 2, 'Bed', 19, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(32, 1, 'Bed', 19, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(83, 4, 'None', 19, 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(5000, 4, 'None', 20, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(2400, 3, 'Room', 20, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(1900, 2, 'None', 20, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(2900, 3, 'Room', 20, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(930, 1, 'Bed', 20, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No'),
(362, 4, 'Bed', 21, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(135, 3, 'Both', 21, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(100, 2, 'Both', 21, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(92, 2, 'Both', 21, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(50, 1, 'None', 21, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(60, 2, 'Bed', 22, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(49, 1, 'Bed', 22, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(65, 2, 'Bed', 22, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(98, 4, 'None', 22, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(73, 3, 'None', 22, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(80, 2, 'None', 23, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'),
(50, 1, 'Room', 23, 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'),
(424, 4, 'None', 23, 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(312, 3, 'Room', 23, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes'),
(190, 3, 'Bed', 23, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(332, 4, 'Bed', 24, 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(315, 4, 'Both', 24, 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No'),
(100, 2, 'Both', 24, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(92, 1, 'Both', 24, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No'),
(302, 3, 'None', 24, 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'),
(513, 4, 'Bed', 25, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(89, 1, 'Bed', 25, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(250, 3, 'Bed', 25, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'),
(160, 2, 'None', 25, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
(53, 1, 'None', 25, 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No');

INSERT INTO employee (First_Name_E, Last_Name_E, SSN_E, IRS_E, A_Street_E, A_Number_E, A_Postal_Code_E, A_City_E)
VALUES 
('Giannis', 'Pitoskas', '389292098', '827392098', 'Pefkon', '15', '14578', 'Ekali'),
('Antonis', 'Papaoikonomou', '389000018', '382932098', 'Thrakis', '19', '14541', 'Kifissia'),
('Giorgos', 'Chionas', '389787828', '389849398', 'Kourtidou', '192', '14213', 'Patissia'),
('Giannis', 'Ste', '912343216', '389272838', 'Samou', '13A', '14549', 'Agios Stefanos'),
('Nikos', 'Koutsoukos', '782392098', '389829398', 'Mpizaniou', '20', '14481', 'Melissia'),
('Marios', 'Morfopoulos', '389888278', '782932098', 'Evrialis', '24', '12368', 'Politeia'),
('Aris', 'Pitoskas', '389286389', '389826378', 'Levidou', '154', '12348', 'Mpampadoupoli'),
('Paraskevas', 'Aleksistilos', '718293876', '234231284', 'Lefkou Prigou', '23A', '51899', 'Thesaloniki'),
('Ioanna', 'Vrettou', '182394983', '782992098', 'Kanari', '15', '14278', 'Ekali'),
('Eleni', 'Alexandraki', '389128373', '518320398', 'Narkissou', '19', '14541', 'Kifissia'),
('Anastasis', 'Deligiannis', '612978378', '212798960', 'Spartis', '1', '11233', 'Patissia'),
('Dimitra', 'Zervaki', '083930792', '953802048', 'Kritis', '13A', '12439', 'Agios Stefanos'),
('Nikos', 'Kalogeropoulos', '007682025', '362387008', 'Rousopoulou', '2', '15281', 'Melissia'),
('Ilias', 'Kiriazis', '271115776', '268674848', 'Zisopoulou', '14', '14543', 'Ekali'),
('Vanos', 'Ntougkanos', '970206400', '230655136', 'Tsilpiridi', '129', '15551', 'Kifissia'),
('Martha', 'Nikolaidi', '305999744', '940762176', 'Gkaziaras', '142', '142223', 'Patissia'),
('Fenia', 'Pappa', '369060928', '791447808', 'Vikaras', '13A', '14439', 'Agios Stefanos'),
('Dionisis', 'Mavrotsoukalos', '937659136', '926102144', 'Kivelis', '22', '12381', 'Melissia'),
('Konstantinos', 'Katakouzinos', '460601152', '959251456', 'Pamvotidas', '35', '34578', 'Ekali'),
('Eleni', 'Vlachaki', '866393472', '806438208', 'Xenias', '44', '14421', 'Kifissia'),
('Vrasidas', 'Chlempouras', '459272448', '052229224', 'Sarantaporou', '22', '14233', 'Patissia'),
('Tasos', 'Vasiliadis', '764314624', '138455808', 'Strofiliou', '13A', '14234', 'Agios Stefanos'),
('Melina', 'Gounari', '885376640', '842308864', 'Kirou', '20', '42345', 'Melissia'),
('Kyriakos', 'Voulgarakis', '674739456', '443138720', 'Proteas', '5', '52248', 'Ekali'),
('Iasonas', 'Krimitzoglou', '203580144', '002095103', 'Skoufa', '11', '24352', 'Kifissia'),
('Vanessa', 'Limperopoulou', '318960320', '072780432', 'Tsakalof', '142', '42343', 'Patissia'),
('Nikos', 'Avocados', '236814624', '990622464', 'Kolokotroni', '13A', '14239', 'Agios Stefanos'),
('Giannis', 'Pigkouinos', '363035032', '444273664', 'Solomou', '30', '42381', 'Melissia');


INSERT INTO works (Start_Date, Finish_Date, Job_Position,  IRS_E_works, Hotel_ID_works)
VALUES
('2018-01-22', '2019-01-21', 'Manager', '827392098', 1),
('2017-02-12', '2019-05-11', 'Manager', '382932098', 2),
('2016-07-04', '2022-08-28', 'Manager', '389849398', 3),
('2015-02-12', '2021-06-03', 'Manager', '389272838', 4),
('2014-08-13', '2020-05-02', 'Manager', '389829398', 5),
('2017-03-22', '2024-04-01', 'Manager', '782932098', 6),
('2017-02-28', '2022-05-12', 'Manager', '389826378', 7),
('2018-03-30', '2021-03-16', 'Manager', '234231284', 8),
('2013-09-12', '2019-02-15', 'Manager', '782992098', 9),
('2014-10-28', '2020-10-05', 'Manager', '518320398', 10),
('2015-09-23', '2020-04-08', 'Manager', '212798960', 11),
('2016-08-21', '2020-11-01', 'Manager', '953802048', 12),
('2017-04-30', '2022-09-18', 'Manager', '362387008', 13),
('2018-02-12', '2022-12-29', 'Manager', '268674848', 14),
('2017-01-22', '2028-01-20', 'Manager', '230655136', 15),
('2017-01-12', '2029-08-22', 'Manager', '940762176', 16),
('2017-07-04', '2025-08-23', 'Manager', '791447808', 17),
('2017-12-12', '2020-01-13', 'Manager', '926102144', 18),
('2017-12-14', '2019-01-13', 'Manager', '959251456', 19),
('2017-11-19', '2025-03-18', 'Manager', '806438208', 20),
('2017-08-23', '2023-10-07', 'Manager', '052229224', 21),
('2016-05-12', '2022-07-05', 'Manager', '138455808', 22),
('2015-01-02', '2021-10-29', 'Manager', '842308864', 23),
('2017-02-08', '2020-10-30', 'Manager', '443138720', 24),
('2018-04-16', '2019-12-22', 'Manager', '002095103', 25),
('2017-03-06', '2020-08-18', 'Manager', '072780432', 5),
('2017-05-09', '2020-09-13', 'Receptionist', '990622464', 8),
('2017-02-07', '2019-10-11', 'Receptionist', '444273664', 22);


/*
CREATE TRIGGER decrement_num_of_hotels_in_hotel_group
BEFORE DELETE ON hotel FOR EACH ROW
SET 
*/

INSERT INTO customer (First_Name_C, Last_Name_C, SSN_C, IRS_C, A_Street_C, A_Number_C, A_Postal_Code_C, A_City_C, User_C, Pass_C)
VALUES 
('Giains', 'Pitosks', '123456783', '142134566', 'Pefkoooon', '1335', '145478', 'Ekalara', 'a','g'),
('Giasis', 'Pitosks', '249238472', '242134556', 'Pefkoon', '1345', '145478', 'Edo','b', 'g'),
('Giadis', 'Pitosks', '319273744', '342134556', 'Pefkorwon', '4135', '145478', 'Ekei','c', 'g'),
('Giafis', 'Pitosks', '492374923', '442314555', 'Pefkoweon', '5135', '145478', 'Pantou','d', 'g'),
('Giagis', 'Pitosks', '541234555', '553425325', 'Pefkqrwoon', '1535', '145478', 'Spitimou','e','g'),
('Giahis', 'Pitosks', '632143255', '621344235', 'Pefkroon', '1635', '145478', 'Spitisou','f', 'g'),
('Giajis', 'Pitosks', '753421512', '743214423', 'Pefkoon', '1375', '145478', 'Panw','g','g');

/*
INSERT INTO reserves(Start_Date, Finish_Date, Paid, IRS_C_reserves, Room_ID_reserves)
VALUES 
("2018-11-12", "2018-11-20", 'No', 1, 100),
("2018-11-13", "2018-11-25", 'No', 2, 109),
("2018-08-18", "2018-10-22", 'No', 3, 108),
("2018-11-13", "2018-11-29", 'No', 4, 105),
("2018-11-12", "2018-11-22", 'No', 5, 103),
("2018-11-12", "2018-11-30", 'No', 6, 111);
*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;